<?php
$Libros=[
    ["code"=> 123, "nombre"=> "Mujercitas", "Autor"=>"Louisa May Alcott","genero"=>"drama", "sinopsis"=>"Amy, Jo, Beth y Meg son cuatro hermanas que atraviesan Massachussets con su madre durante la Guerra Civil, unas vacaciones que realizan sin su padre evangelista itinerante. Durante estas vacaciones las adolescentes descubren el amor y la importancia de los lazos familiares.
    ", "portada"=>"images/mujercitas.webp", "pages"=>"500", "price"=>"18000"],
    ["code"=> 1234, "nombre"=> "Un cuento perfecto", "Autor"=>"Elizabeth Benavent","genero"=>"romance", "sinopsis"=>"Margot y David provienen de mundos diferentes. Ella es heredera de un imperio hotelero. Él debe desempeñar tres trabajos para llegar a fin de mes. Pero cuando sus caminos se unen, se dan cuenta de que solo entre ellos pueden ayudarse a recuperar el amor de sus vidas.", "portada"=>"images/cuentoperfecto.webp", "pages"=>"850", "price"=>"25000"],
    ["code"=> 12345, "nombre"=> "Los siete maridos de Evelyn Hugo", "Autor"=>"Taylor Red","genero"=>"drama", "sinopsis"=>"En una esperada entrevista con un joven periodista, Evelyn Hugo, una envejecida estrella de Hollywood, descorre el telón de sus siete matrimonios, y mientras cuenta historias de escándalos, traiciones y desgracias de Hollywood, desvela verdades impactantes sobre su propia vida y la de todos los que la rodean", "portada"=>"images/evelyn.jpg", "pages"=>"500", "price"=>"21000"],
    ["code"=> 123456, "nombre"=> "Tan poca vida", "Autor"=>"Hanya Yanagihara","genero"=>"drama", "sinopsis"=>"Tan poca vida, una historia que recorre más de tres decadas de amistad en la vida de cuatro hombres que crecen juntos en Manhattan. Cuatro hombres que tienen que sobrevivir al fracaso y al exito y que, a lo largo de los años, aprenden a sobreponerse a las crisis económicas, sociales y emocionales. Cuatro hombres que comparten una idea muy peculiar de la intimidad, una manera de estar juntos hecha de pocas palabras y muchos gestos. Cuatro hombres cuya relación la autora", "portada"=>"images/pocavida.webp", "pages"=>"1000", "price"=>"39000"],
    ["code"=> 1234567, "nombre"=> "Twisted Love", "Autor"=>"Anna Huang","genero"=>"romance", "sinopsis"=>"Alex Volkov vive asediado por una tragedia que lo ha perseguido toda su vida. Una vida sin tiempo para el amor. Pero el día que se ve obligado a cuidar de la hermana de su mejor amigo, empieza a sentir algo.", "portada"=>"images/twistedlove.jpg", "pages"=>"550", "price"=>"24000"],
    ["code"=> 12345678, "nombre"=> "Una corte de rosas y espinas ", "Autor"=>"Sarah J Maas","genero"=>"fantasía", "sinopsis"=>"Cuando la cazadora de diecinueve años llamada Feyre mata a un lobo en el bosque, una criatura misteriosa parecida a una bestia llega para cobrar su recompensa. Es así como Feyre es capturada y llevada a una tierra mágica que creía que solo existir en los cuentos de hadas.", "portada"=>"images/acotar.jpg", "pages"=>"480", "price"=>"28000"],
    ["code"=> 2345678, "nombre"=> "Una corte de llamas plateadas", "Autor"=>"Sarah J Maas","genero"=>"fantasía", "sinopsis"=>"
    Nesta Archeron, forzada a convertirse en alta fae, lucha por encontrar su lugar en un mundo peligroso. Marcada por su temperamento y los horrores de la guerra con Hybern, Nesta enfrenta un desafío aún mayor cuando Cassian, miembro de la Corte Noche, es asignado para entrenarla. Entre ellos surge una intensa pasión mientras las reinas humanas traidoras forman una nueva alianza que amenaza la frágil paz. Nesta y Cassian deberán superar sus pasados para enfrentarse a los monstruos interiores y exteriores, buscando aceptación y curación juntos.", "portada"=>"images/corte-de-llamas-plateada-sarah-j-maas.jpg", "pages"=>"816", "price"=>"48000"],
    ["code"=>345678, "nombre"=> "El niño con el pijama de rayas", "Autor"=>"John Boyne","genero"=>"drama", "sinopsis"=>"Un niño alemán de nueve años que se muda con su familia cerca de un campo de concentración durante la Segunda Guerra Mundial. Desde su nueva casa, Bruno se siente solo hasta que un día conoce a un niño llamado Shmuel que vive al otro lado de una cerca y viste un pijama de rayas. Los dos niños desarrollan una amistad a pesar de la valla que los separa. A medida que Bruno descubre la verdad sobre el mundo en el que vive y el destino de su amigo, la historia culmina en un final impactante que revela las realidades de la guerra y el Holocausto desde la perspectiva de un niño..", "portada"=>"images/el-nino-con-el-pijama-de-rayas.jpg", "pages"=>"480", "price"=>"8000"],
    ["code"=>3456789, "nombre"=> "Magnolia Parks", "Autor"=>"Jessa Hastings","genero"=>"drama", "sinopsis"=>"Bienvenido a la alta sociedad Londinense, donde la mesa está servida y los corazones arden... ¡Llega el fenómeno romántico de TikTok! ¿Cuántos amores te tocan en una vida? Ella es una preciosa, rica, egoísta y un poco caprichosa socialité londinense.Él es el chico malo más fotografiado de Inglaterra, y su rompecorazones particular. Todo el mundo sabe que Magnolia Parks y BJ Ballentine están hechos el uno para el otro. Pero el destino no parece estar de su parte. Por mucho que Magnolia intente poner distancia saliendo con otra gente y BJ se acueste con otras chicas para vengarse, siempre acaban volviendo a los brazos del otro.Entre las cicatrices de un viejo amor y los secretos que por ellas asoman, Magnolia y BJ se verán obligados a encararse para responder a la pregunta que llevan toda la vida evitando: ¿Cuántos amores tienes realmente en una vida?", "portada"=>"images/magnolia-parks.jpg", "pages"=>"600", "price"=>"25000"],
    ["code"=>45678, "nombre"=> "Binding 13", "Autor"=>"Chloe Walsh","genero"=>"romance", "sinopsis"=>"La vida nunca ha sido fácil para Shannon Lynch.
    Atrapada en un torbellino de sentimientos hacia él y desesperada por pasar desapercibida, Shannon se convierte una vez más en el blanco del acoso, pero la flamante estrella del rugby irlandés resulta ser un aliado de lo más inesperado.", "portada"=>"images/binding-13.jpg", "pages"=>"680", "price"=>"50000"],
    ["code"=>456789, "nombre"=> "Alas de Hierro", "Autor"=>"Rebecca Yarros","genero"=>"fantasía", "sinopsis"=>"Violet Sorrengail enfrenta su primer año en el Colegio de Guerra de Basgiath, donde la Trilla fue solo el comienzo de pruebas diseñadas para eliminar a los no aptos. Ahora debe soportar un entrenamiento brutal bajo la mirada del nuevo vicecomandante, que busca exponer su debilidad a menos que traicione a su amado. Aunque su cuerpo es más frágil, Violet cuenta con su ingenio y determinación. Enfrenta líderes que olvidan la lección principal de Basgiath: los jinetes de dragones establecen sus propias reglas. Su voluntad de sobrevivir no bastará, ya que conoce un secreto oculto en el colegio que amenaza con consumirlos a todos.", "portada"=>"images/alas-de-hierro-empireo-2-rebecca-yarros.jpg", "pages"=>"1000", "price"=>"34000"],
    ["code"=>456781, "nombre"=> "9 de Noviembre", "Autor"=>"Collen Hoover","genero"=>"romance", "sinopsis"=>"Una historia tragica y romantica, Nunca podrás encontrarte a ti misma si estás perdida en alguien más Fallon conoce a Ben, un aspirante a novelista, el día antes de su mudanza al otro lado del país. Su atracción inmediata los lleva a pasar juntos el último día de Fallon en Los Ángeles, y su azarosa vida se convierte en la inspiración creativa que Ben siempre ha buscado para su novela. A pesar del tiempo, y en medio de las diversas relaciones y tribulaciones de sus propias vidas, ellos se siguen encontrando en la misma fecha cada año. Hasta que un día, Fallon comienza a dudar si Ben ha sido realmente honesto con ella o si sólo está fabricando una realidad perfecta en busca del último giro de su trama. ", "portada"=>"images/9-november.coolen-hoover.jpeg", "pages"=>"600", "price"=>"30000"]
];
$json = json_encode($Libros);
    echo $json;