<?php
$Libros=[
    ["code"=> 123, "nombre"=> "Mujercitas", "Autor"=>"Louisa May Alcott","genero"=>"drama", "sinopsis"=>"Amy, Jo, Beth y Meg son cuatro hermanas que atraviesan Massachussets con su madre durante la Guerra Civil, unas vacaciones que realizan sin su padre evangelista itinerante. Durante estas vacaciones las adolescentes descubren el amor y la importancia de los lazos familiares.
    ", "portada"=>"images/mujercitas.webp", "pages"=>"500", "price"=>"18000"],
    ["code"=> 1234, "nombre"=> "Un cuento perfecto", "Autor"=>"Elizabeth Benavent","genero"=>"romance", "sinopsis"=>"Margot y David provienen de mundos diferentes. Ella es heredera de un imperio hotelero. Él debe desempeñar tres trabajos para llegar a fin de mes. Pero cuando sus caminos se unen, se dan cuenta de que solo entre ellos pueden ayudarse a recuperar el amor de sus vidas.", "portada"=>"images/cuentoperfecto.webp", "pages"=>"850", "price"=>"25000"],
    ["code"=> 12345, "nombre"=> "Los siete maridos de Evelyn Hugo", "Autor"=>"Taylor Red","genero"=>"drama", "sinopsis"=>"En una esperada entrevista con un joven periodista, Evelyn Hugo, una envejecida estrella de Hollywood, descorre el telón de sus siete matrimonios, y mientras cuenta historias de escándalos, traiciones y desgracias de Hollywood, desvela verdades impactantes sobre su propia vida y la de todos los que la rodean", "portada"=>"images/evelyn.jpg", "pages"=>"500", "price"=>"21000"],
    ["code"=> 123456, "nombre"=> "Tan poca vida", "Autor"=>"Hanya Yanagihara","genero"=>"drama", "sinopsis"=>"Tan poca vida, una historia que recorre más de tres decadas de amistad en la vida de cuatro hombres que crecen juntos en Manhattan. Cuatro hombres que tienen que sobrevivir al fracaso y al exito y que, a lo largo de los años, aprenden a sobreponerse a las crisis económicas, sociales y emocionales. Cuatro hombres que comparten una idea muy peculiar de la intimidad, una manera de estar juntos hecha de pocas palabras y muchos gestos. Cuatro hombres cuya relación la autora", "portada"=>"images/pocavida.webp", "pages"=>"1000", "price"=>"39000"],
    ["code"=> 1234567, "nombre"=> "Twisted Love", "Autor"=>"Anna Huang","genero"=>"romance", "sinopsis"=>"Alex Volkov vive asediado por una tragedia que lo ha perseguido toda su vida. Una vida sin tiempo para el amor. Pero el día que se ve obligado a cuidar de la hermana de su mejor amigo, empieza a sentir algo.", "portada"=>"images/twistedlove.jpg", "pages"=>"550", "price"=>"24000"],
    ["code"=> 12345678, "nombre"=> "Una corte de rosas y espinas ", "Autor"=>"Sarah J Maas","genero"=>"fantasía", "sinopsis"=>"Cuando la cazadora de diecinueve años llamada Feyre mata a un lobo en el bosque, una criatura misteriosa parecida a una bestia llega para cobrar su recompensa. Es así como Feyre es capturada y llevada a una tierra mágica que creía que solo existir en los cuentos de hadas.", "portada"=>"images/acotar.jpg", "pages"=>"480", "price"=>"28000"]
];
